# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Id')),
                ('manufacturer', models.CharField(max_length=256, null=True, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=256, null=True, verbose_name='Model')),
                ('color', models.CharField(blank=True, max_length=256, null=True, verbose_name='Color')),
                ('year', models.IntegerField(blank=True, verbose_name='Year')),
                ('mileage', models.IntegerField(blank=True, verbose_name='Mileage')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Snoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256, null=True, verbose_name='Model')),
                ('manufacturer', models.CharField(max_length=256, null=True, verbose_name='Manufacturer')),
                ('year_min', models.IntegerField(blank=True, null=True, verbose_name='Year min')),
                ('year_max', models.IntegerField(blank=True, null=True, verbose_name='Year max')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snoops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snoop',
                'verbose_name_plural': 'Snoops',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='snoop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carfinderapp.Snoop'),
        ),
    ]
