# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfinderapp', '0004_auto_20180227_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='snoop',
            name='mileage_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mileage max'),
        ),
        migrations.AddField(
            model_name='snoop',
            name='mileage_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mileage min'),
        ),
    ]
